### ISSUE TITLE
generate synthetic test-data from gazebo simulator

### ISSUE THREAD

**Issue by fabolhak** [tum-phoenix/drive_ml#10]
From gazebo simulation generate:
- class labels
- bounding boxes
- images

https://github.com/tum-phoenix/drive_sim_road_generation

For naming and storing conventions, please follow the [GTSRB structure](http://benchmark.ini.rub.de/?section=gtsrb&subsection=dataset#Structure).

**Comment by MaslinuPoimal** [comment]
I have added the sign_label_plugin in [drive_gazebo_plugins](https://github.com/tum-phoenix/drive_gazebo_plugins). Detailed instructions on how to run can be found there.
