### ISSUE TITLE
evaluate Tensorflow Object Detection API

### ISSUE THREAD

**Issue by fabolhak** [tum-phoenix/drive_ml#14]
Google recently announced its new Object Detection API.  It could be very interessting for us. 

The tools include:
- Faster-RCNN with NASNet-A image featurization
- Single Shot Multibox Detector (SSD) with MobileNet,
- SSD with Inception V2,
- Region-Based Fully Convolutional Networks (R-FCN) with Resnet 101,
- Faster RCNN with Resnet 101,
- Faster RCNN with Inception Resnet v2

More infos:
https://github.com/tensorflow/models/tree/master/research/object_detection

**Comment by MaslinuPoimal** [comment]
Done, everything but tiny-Yolo/SSD with similar small backends is not feasible on the TX2.

Tiny Yolo V3 runs quite well at 26FPS and gives promising results (even with the tiny amount of training data).
