### ISSUE TITLE
Data Analytics - Class and Boundingbox statistics

### ISSUE THREAD

**Issue by xXBasti** [tum-phoenix/drive_ml#15]
Currently, we have included most public and private datasets. The notebook with the labels and conversion examples is available [here](https://github.com/tum-phoenix/drive_ml/blob/master/tf_object_detection/convert_datasets.ipynb). Dataset evaluation is found [here](https://github.com/tum-phoenix/drive_ml/blob/master/tf_object_detection/Data%20Augumentation.ipynb). 

Available public datasets:
- GTSDB (German Traffic Sign Detection Benchmark)
- LISA (Laboratory for Intelligent and Safe Automobiles)
- BTSD (Belgian Traffic Sign Dataset)
- STS (Swedish Traffic Sign Dataset)
- DITS (Dataset of Italian Traffic Signs)
- RTSD (Russian Traffic Sign Dataset)

Todo:
- [ ] add conversion dict for Mapillary Traffic Sign dataset
- [ ] add evaluation for Mapillary traffic sign dataset
- [ ] add conversion dict for Berkeley Deep Drive dataset
- [ ] add evaluation for Berkeley Deep Drive dataset

**Comment by wnklb** [comment]
Added a notebook in 0d34c56. This gives a first insight into the class distribution of the 'Bosch Dataset'. Gonna extend this with further plots of the bounding box distribution.
