### ISSUE TITLE
Pipeline for tensorflow

### ISSUE THREAD

**Issue by xXBasti** [tum-phoenix/drive_ml#17]
Develop a pipeline for learning
* data preprocessing
* parameter handling
* training validation test routine
* evaluation / visualization tool (e.g. tensorboard)

Create a docker image where everything works.

**Comment by fabolhak** [comment]
for hyperparameter search: http://hyperopt.github.io/hyperopt/

**Comment by fabolhak** [comment]
evaluate MS pipeline first: https://github.com/tum-phoenix/drive_ml/issues/18

**Comment by xXBasti** [comment]
Closed and replaced by other issues
