### ISSUE TITLE
TrafficSigns: [object detection] Improve the current YOLOv3 script

### ISSUE THREAD

**Issue by Christiaan1990** [tum-phoenix/drive_ml#27]
#### Goal:
Improve the accuracy of the current YOLOv3 by first getting the baseline performance with open source datasets and the carolocup dataset, then find out which problems exist, and finally add improvements/test resutls. 

#### Assigments:
-  analyze the current script
- determine out-of-the-box performance for the open source dataset and the carolocup dataset
- understand where the model can be improved
- retrain/retest
 - documentation in the TUM-Wiki: [https://wiki.tum.de/display/phoenix/Machine+Learning](url)

#### Notes:
- File: /drive_ml/blob/master/tf_object_detection/Train Yolo3.ipynb
- information about the current YOLOv3 implementation and the current datasets: https://wiki.tum.de/display/phoenix

**Comment by MaslinuPoimal** [comment]
Note: a nice starting issues would be to try training with the data from the open-source datasets and compare the performance.
