### ISSUE TITLE
LaneDetection: Hough Transform - Implement/Test lane detection

### ISSUE THREAD

**Issue by Christiaan1990** [tum-phoenix/drive_ml#32]
#### Goal:
Implement and test the "Hough Transform" algorithm on the offline datasets CULane and TuSimple. Note: this is a classical approach and no machine learning. 

#### Assigments:
- Understand the algorithm
- Understand the dataset
- Evaluate the performance of the algorithm on the datasets
 - documentation in the TUM-Wiki: [https://wiki.tum.de/display/phoenix/Machine+Learning](url)

#### Notes:
- See approach 1 of https://towardsdatascience.com/tutorial-build-a-lane-detector-679fd8953132
- Datasets:
1) https://xingangpan.github.io/projects/CULane.html
2) https://github.com/TuSimple/tusimple-benchmark/issues/3

**Comment by MaslinuPoimal** [comment]
Note: the current version contains quite a lot of optimizations for the cup environment, but we can definitely try this.
