### ISSUE TITLE
Design a network for localsation

### ISSUE THREAD

**Issue by xXBasti** [tum-phoenix/drive_ml#7]
Output should be (n,4) range each 0 to 64 (max value of our pixels).

1. Try the Classification NN with a Localsiation Layer, output linearisation with (n,4) instead of (n,44)
2. Literatur Reseach to the topic of localisation (optional), please brief the rest of the team.
3. Train with the picture in picture data set

**Comment by MaslinuPoimal** [comment]
I'll take a look at this, might be able to combine it with a lecture.
